MobileShop-war/src/java/com/iviet/controllor/OrdersEntityController.java
package com.iviet.controllor;

import com.iviet.entity.OrdersEntity;
import com.iviet.controllor.util.JsfUtil;
import com.iviet.controllor.util.PaginationHelper;
import com.iviet.stub.OrdersEntityFacadeStub;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "ordersEntityController")
@SessionScoped
public class OrdersEntityController implements Serializable {

    private OrdersEntity current;
    private DataModel items = null;
//Delete    @EJB
    private com.iviet.stub.OrdersEntityFacadeStub ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public OrdersEntityController() {
        ejbFacade = new OrdersEntityFacadeStub();
    }

    public OrdersEntity getSelected() {
        if (current == null) {
            current = new OrdersEntity();
            selectedItemIndex = -1;
        }
        return current;
    }

    private OrdersEntityFacadeStub getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new OrdersEntity();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (OrdersEntity) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("OrdersEntityDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    @FacesConverter(forClass = OrdersEntity.class)
    public static class OrdersEntityControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            OrdersEntityController controller = (OrdersEntityController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "ordersEntityController");
            return controller.ejbFacade.find(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof OrdersEntity) {
                OrdersEntity o = (OrdersEntity) object;
                return getStringKey(o.getOrderId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + OrdersEntity.class.getName());
            }
        }

    }

}

MobileShop-war/web/ordersEntity/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/back_end_tmpl.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateOrdersEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_orderId}" for="orderId" />
                    <h:inputText id="orderId" value="#{ordersEntityController.selected.orderId}" title="#{bundle.CreateOrdersEntityTitle_orderId}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_orderId}"/>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_date}" for="date" />
                    <h:inputText id="date" value="#{ordersEntityController.selected.date}" title="#{bundle.CreateOrdersEntityTitle_date}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_date}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_status}" for="status" />
                    <h:inputText id="status" value="#{ordersEntityController.selected.status}" title="#{bundle.CreateOrdersEntityTitle_status}" />
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_total}" for="total" />
                    <h:inputText id="total" value="#{ordersEntityController.selected.total}" title="#{bundle.CreateOrdersEntityTitle_total}" />
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_customerId}" for="customerId" />
                    <h:selectOneMenu id="customerId" value="#{ordersEntityController.selected.customerId}" title="#{bundle.CreateOrdersEntityTitle_customerId}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_customerId}">
                        <f:selectItems value="#{customersEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_paymentId}" for="paymentId" />
                    <h:selectOneMenu id="paymentId" value="#{ordersEntityController.selected.paymentId}" title="#{bundle.CreateOrdersEntityTitle_paymentId}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_paymentId}">
                        <f:selectItems value="#{paymentEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateOrdersEntityLabel_shipmentId}" for="shipmentId" />
                    <h:selectOneMenu id="shipmentId" value="#{ordersEntityController.selected.shipmentId}" title="#{bundle.CreateOrdersEntityTitle_shipmentId}" required="true" requiredMessage="#{bundle.CreateOrdersEntityRequiredMessage_shipmentId}">
                        <f:selectItems value="#{shipmentEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{ordersEntityController.create}" value="#{bundle.CreateOrdersEntitySaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{ordersEntityController.prepareList}" value="#{bundle.CreateOrdersEntityShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateOrdersEntityIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MobileShop-war/web/ordersEntity/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/back_end_tmpl.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditOrdersEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_orderId}" for="orderId" />
                    <h:inputText id="orderId" value="#{ordersEntityController.selected.orderId}" title="#{bundle.EditOrdersEntityTitle_orderId}" required="true" requiredMessage="#{bundle.EditOrdersEntityRequiredMessage_orderId}"/>
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_date}" for="date" />
                    <h:inputText id="date" value="#{ordersEntityController.selected.date}" title="#{bundle.EditOrdersEntityTitle_date}" required="true" requiredMessage="#{bundle.EditOrdersEntityRequiredMessage_date}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_status}" for="status" />
                    <h:inputText id="status" value="#{ordersEntityController.selected.status}" title="#{bundle.EditOrdersEntityTitle_status}" />
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_total}" for="total" />
                    <h:inputText id="total" value="#{ordersEntityController.selected.total}" title="#{bundle.EditOrdersEntityTitle_total}" />
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_customerId}" for="customerId" />
                    <h:selectOneMenu id="customerId" value="#{ordersEntityController.selected.customerId}" title="#{bundle.EditOrdersEntityTitle_customerId}" required="true" requiredMessage="#{bundle.EditOrdersEntityRequiredMessage_customerId}">
                        <f:selectItems value="#{customersEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_paymentId}" for="paymentId" />
                    <h:selectOneMenu id="paymentId" value="#{ordersEntityController.selected.paymentId}" title="#{bundle.EditOrdersEntityTitle_paymentId}" required="true" requiredMessage="#{bundle.EditOrdersEntityRequiredMessage_paymentId}">
                        <f:selectItems value="#{paymentEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditOrdersEntityLabel_shipmentId}" for="shipmentId" />
                    <h:selectOneMenu id="shipmentId" value="#{ordersEntityController.selected.shipmentId}" title="#{bundle.EditOrdersEntityTitle_shipmentId}" required="true" requiredMessage="#{bundle.EditOrdersEntityRequiredMessage_shipmentId}">
                        <f:selectItems value="#{shipmentEntityController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{ordersEntityController.update}" value="#{bundle.EditOrdersEntitySaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditOrdersEntityViewLink}"/>
                <br />
                <h:commandLink action="#{ordersEntityController.prepareList}" value="#{bundle.EditOrdersEntityShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditOrdersEntityIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MobileShop-war/web/ordersEntity/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/back_end_tmpl.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListOrdersEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListOrdersEntityEmpty}" rendered="#{ordersEntityController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{ordersEntityController.items.rowCount > 0}">
                    <h:outputText value="#{ordersEntityController.pagination.pageFirstItem + 1}..#{ordersEntityController.pagination.pageLastItem + 1}/#{ordersEntityController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{ordersEntityController.previous}" value="#{bundle.Previous} #{ordersEntityController.pagination.pageSize}" rendered="#{ordersEntityController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{ordersEntityController.next}" value="#{bundle.Next} #{ordersEntityController.pagination.pageSize}" rendered="#{ordersEntityController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{ordersEntityController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_orderId}"/>
                            </f:facet>
                            <h:outputText value="#{item.orderId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_date}"/>
                            </f:facet>
                            <h:outputText value="#{item.date}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_status}"/>
                            </f:facet>
                            <h:outputText value="#{item.status}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_total}"/>
                            </f:facet>
                            <h:outputText value="#{item.total}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_customerId}"/>
                            </f:facet>
                            <h:outputText value="#{item.customerId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_paymentId}"/>
                            </f:facet>
                            <h:outputText value="#{item.paymentId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListOrdersEntityTitle_shipmentId}"/>
                            </f:facet>
                            <h:outputText value="#{item.shipmentId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{ordersEntityController.prepareView}" value="#{bundle.ListOrdersEntityViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ordersEntityController.prepareEdit}" value="#{bundle.ListOrdersEntityEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{ordersEntityController.destroy}" value="#{bundle.ListOrdersEntityDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{ordersEntityController.prepareCreate}" value="#{bundle.ListOrdersEntityCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListOrdersEntityIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

MobileShop-war/web/ordersEntity/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="./../template/back_end_tmpl.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewOrdersEntityTitle}"></h:outputText>
        </ui:define>
        <ui:define name="content">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_orderId}"/>
                    <h:outputText value="#{ordersEntityController.selected.orderId}" title="#{bundle.ViewOrdersEntityTitle_orderId}"/>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_date}"/>
                    <h:outputText value="#{ordersEntityController.selected.date}" title="#{bundle.ViewOrdersEntityTitle_date}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_status}"/>
                    <h:outputText value="#{ordersEntityController.selected.status}" title="#{bundle.ViewOrdersEntityTitle_status}"/>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_total}"/>
                    <h:outputText value="#{ordersEntityController.selected.total}" title="#{bundle.ViewOrdersEntityTitle_total}"/>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_customerId}"/>
                    <h:outputText value="#{ordersEntityController.selected.customerId}" title="#{bundle.ViewOrdersEntityTitle_customerId}"/>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_paymentId}"/>
                    <h:outputText value="#{ordersEntityController.selected.paymentId}" title="#{bundle.ViewOrdersEntityTitle_paymentId}"/>
                    <h:outputText value="#{bundle.ViewOrdersEntityLabel_shipmentId}"/>
                    <h:outputText value="#{ordersEntityController.selected.shipmentId}" title="#{bundle.ViewOrdersEntityTitle_shipmentId}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{ordersEntityController.destroyAndView}" value="#{bundle.ViewOrdersEntityDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewOrdersEntityEditLink}"/>
                <br />
                <h:commandLink action="#{ordersEntityController.prepareCreate}" value="#{bundle.ViewOrdersEntityCreateLink}" />
                <br />
                <h:commandLink action="#{ordersEntityController.prepareList}" value="#{bundle.ViewOrdersEntityShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewOrdersEntityIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>